version: "2"

services:
  tests:
    build:
      context: .
      args:
        - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
        - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    image: keboola/oracle-table-exporter
    volumes:
      - ./:/code
    environment:
      DB_HOST: oracle
      DB_PORT: 1521
      DB_USER: system
      DB_PASSWORD: oracle
      DB_DATABASE: XE
    command: /code/start.sh
    links:
      - oracle

  oracle:
    build: https://github.com/keboola/docker-oracle-xe-11g.git
    image: wnameless/oracle-xe-11g-r2
    ports:
      - "8080:8080"
      - "1521:1521"
